security.jwt:
  tokenExpirationTime: 60 # Minutes == 1 hour
  refreshTokenExpTime: 10080 # Minutes == 1 week
  tokenIssuer: http://localhost:4200
  tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus

cloudinary:
  cloudName: dlucqoyh6
  apiKey: 124984516762691
  apiSecret: ssgxtk-hGGfB7qOYwTqOXqutXN8